# Generated by Django 4.2.7 on 2023-12-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_rename_product_eventprice_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventprice", old_name="price", new_name="event_price",
        ),
        migrations.RenameField(
            model_name="eventprice", old_name="event", new_name="event_product",
        ),
    ]
