# Generated by Django 4.1 on 2023-09-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="city",
            field=models.CharField(blank=True, max_length=30, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="venue",
            name="state",
            field=models.CharField(blank=True, max_length=30, verbose_name="State"),
        ),
    ]
