# Generated by Django 4.2.7 on 2023-12-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_rename_price_eventprice_event_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_ticket_type",
            field=models.CharField(default="adult", max_length=50),
        ),
    ]
