# Generated by Django 4.2.7 on 2024-07-23 20:16

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0002_alter_subscribers_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "message",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("recipients", models.ManyToManyField(to="letter.subscribers")),
            ],
        ),
    ]
