# Generated by Django 4.2.7 on 2024-07-15 00:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0002_alter_subscribers_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", ckeditor.fields.RichTextField()),
                ("recipients", models.ManyToManyField(to="letter.subscribers")),
            ],
        ),
    ]
