# Generated by Django 4.1 on 2023-10-08 21:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pollsapp", "0002_voter"),
    ]

    operations = [
        migrations.RenameModel(old_name="Voter", new_name="Vote",),
    ]
