# Generated by Django 4.1 on 2023-10-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pollsapp", "0004_rename_poll_vote_question_rename_user_vote_voter"),
    ]

    operations = [
        migrations.RenameField(model_name="choice", old_name="vote", new_name="votes",),
    ]
