# Generated by Django 4.2.7 on 2023-12-12 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "big_forum",
            "0009_remove_bf_post_user_bf_post_author_bf_post_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bf_post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
