# Generated by Django 4.2.7 on 2023-12-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0019_alter_comment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author", old_name="author", new_name="user",
        ),
        migrations.AlterField(
            model_name="bf_post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="big_forum.author"
            ),
        ),
    ]
