# Generated by Django 4.2.7 on 2023-12-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0020_rename_author_author_user_alter_bf_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bf_post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="big_forum.author",
            ),
        ),
    ]
