# Generated by Django 4.2.7 on 2023-12-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0021_alter_bf_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bf_post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="big_forum.author"
            ),
        ),
    ]
