# Generated by Django 4.2.7 on 2024-07-07 22:16

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0024_alter_bf_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_pic",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=100,
                scale=None,
                size=[50, 80],
                upload_to="authors",
            ),
        ),
        migrations.AlterField(
            model_name="bf_post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="big_forum.author"
            ),
        ),
    ]
