# Generated by Django 4.2.7 on 2023-12-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0010_alter_bf_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="bf_post",
            name="fullname",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
