# Generated by Django 4.2.7 on 2023-12-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0014_alter_bf_post_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="bf_post", name="user_id",),
    ]
