# Generated by Django 4.2.7 on 2024-07-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customer_delete_member"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
