# Generated by Django 4.1 on 2023-10-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pollsapp", "0005_rename_vote_choice_votes"),
    ]

    operations = [
        migrations.RenameField(model_name="choice", old_name="votes", new_name="vote",),
        migrations.DeleteModel(name="Vote",),
    ]
