# Generated by Django 4.2.7 on 2023-12-14 12:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("letter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailmessage",
            name="message",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
