# Generated by Django 4.1 on 2023-09-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_venue_city_venue_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="email_address",
            field=models.EmailField(blank=True, max_length=50, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="phone",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Contact Phone"
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="web",
            field=models.URLField(blank=True, verbose_name="Website Address"),
        ),
    ]
