# Generated by Django 4.1 on 2023-09-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="not_approved",
            field=models.BooleanField(default=True, verbose_name="Not Approved"),
        ),
    ]
