# Generated by Django 4.2.7 on 2023-12-28 15:34

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_eventtag_eventprice_eventpaymenthistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event", options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(model_name="event", name="price",),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event", name="quantity", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, to="events.eventtag"),
        ),
        migrations.AddField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to=events.models.get_image_filename
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event", name="url", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
