# Generated by Django 4.2.7 on 2023-12-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_event_event_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="age_group",
            field=models.CharField(default="Adult", max_length=20),
        ),
        migrations.AddField(
            model_name="event",
            name="event_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
