# Generated by Django 4.2.7 on 2023-12-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_age_group_event_event_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("tickets", models.ManyToManyField(to="events.event")),
            ],
        ),
    ]
