# Generated by Django 4.2.7 on 2023-12-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0007_rename_user_bf_post_author_remove_author_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bf_post", old_name="author", new_name="user",
        ),
    ]
