# Generated by Django 4.2.7 on 2023-12-12 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("big_forum", "0008_rename_author_bf_post_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="bf_post", name="user",),
        migrations.AddField(
            model_name="bf_post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bf_post", name="user_id", field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(name="Author",),
    ]
