# Generated by Django 4.2.7 on 2023-12-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("big_forum", "0017_alter_comment_user_alter_reply_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="big_forum.author"
            ),
        ),
    ]
