# Generated by Django 4.2.7 on 2023-12-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymenthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
