# Generated by Django 4.2.7 on 2023-12-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymenthistory_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_status",
            field=models.CharField(
                choices=[("P", "pending"), ("C", "completed"), ("F", "failed")],
                default="P",
                max_length=20,
            ),
        ),
    ]
