# Generated by Django 4.2.7 on 2023-12-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_paymenthistory_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
